name: sub-store
services:
    sub-store:
        stdin_open: true
        tty: true
        restart: always
        environment:
            - SUB_STORE_PUSH_SERVICE=
            - SUB_STORE_BACKEND_SYNC_CRON=55 23 * * *
            - SUB_STORE_FRONTEND_BACKEND_PATH=/2cXaAxRGfddmGz2yx1wA
        ports:
            - 127.0.0.1:3001:3001
        volumes:
            - /root/sub-store-data:/opt/app/data
        container_name: sub-store
        image: xream/sub-store
