lzc-sdk-version: "0.1"
name: Sub Store
package: coder.czyt.app.sub-store
version: 2.19.9
description: Advanced Subscription Manager
homepage: https://github.com/sub-store-org/Sub-Store
author: sub-store-org
application:
  subdomain: sub-store
  background_task: true
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  routes:
    - /=http://sub-store:3001/
  public_path:
    - /
services:
  sub-store:
    image: docker.hlmirror.com/xream/sub-store:2.19.9
    environment:
      - SUB_STORE_PUSH_SERVICE=
      - SUB_STORE_BACKEND_SYNC_CRON=55 23 * * *
      - SUB_STORE_BACKEND_API_PORT=3000
      - SUB_STORE_FRONTEND_PORT=3001
      - SUB_STORE_BACKEND_API_HOST=0.0.0.0
      - SUB_STORE_FRONTEND_HOST=0.0.0.0
      - SUB_STORE_FRONTEND_BACKEND_PATH=/2cXaAxRGfddmGz2yx1wA
    binds:
      - /lzcapp/var/data:/opt/app/data
