name: Sub Store
package: community.app.sub-store
version: 2.36.17
min_os_version: 1.5.0
description: "Advanced subscription manager"
license: AGPL-3.0
homepage: https://github.com/sub-store-org/Sub-Store
author: sub-store-org
unsupported_platforms:
  - ios
  - android
locales:
  en:
    name: "Sub Store"
    description: "Advanced subscription manager"
  zh:
    name: "Sub Store"
    description: "高级订阅管理工具"
